### ISSUE TITLE
Error while running `wasm-pack test --headless --chrome`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/js-chain-libs#21] opened 2019-08-13 08:14 UTC
**Describe the bug**
I got an error while trying to run the tests as described on Readme (https://github.com/input-output-hk/js-chain-libs)

**To Reproduce**
1. Go to `/input-output-hk/js-chain-libs` folder
2. execute `wasm-pack test --headless --chrome`

```
error: failed to find element reference in response
error: test failed, to rerun pass '--test web'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 1
```

**Expected behavior**
Many tests are run and pass.

**Additional context**

[logs.txt](https://github.com/input-output-hk/js-chain-libs/files/3495914/logs.txt)

**Comment by enzoc4** [comment] 2019-08-13 14:14
Interesting, I can't reproduce this... Can you post the logs of the command after setting the env bar RUST_LOG to wasm_bindgen_test_runner?
I think in windows you have to do something like
```cmd
set RUST_LOG=wasm_bindgen_test_runner
wasm-pack test --headless --chrome
```

**Comment by dorin100** [comment] 2019-08-13 14:40
```
D:\iohk\otherProjects\js-chain-libs>set RUST_LOG=wasm_bindgen_test_runner
```
```
D:\iohk\otherProjects\js-chain-libs>wasm-pack test --headless --chrome
[INFO]: Checking for the Wasm target...
    Finished dev [unoptimized + debuginfo] target(s) in 1.69s
[INFO]: Installing wasm-bindgen...
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running target\wasm32-unknown-unknown\debug\deps\js_chain_libs-c9ac9bbf7562ba57.wasm
no tests to run!
     Running target\wasm32-unknown-unknown\debug\deps\web-0c214e07a28f3079.wasm
Running headless tests in Chrome with `C:\Users\Dorin\AppData\Local\.wasm-pack\chromedriver-87c19a493f3a2690\chromedriver.exe`
[2019-08-13T14:39:20Z DEBUG wasm_bindgen_test_runner::headless] executing "C:\\Users\\Dorin\\AppData\\Local\\.wasm-pack\\chromedriver-87c19a493f3a2690\\chromedriver.exe" "--p
ort=57722"
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] POST /session {"desiredCapabilities":{"goog:chromeOptions":{"args":["headless","disable-dev-shm-usage","no-san
dbox"]}}}

DevTools listening on ws://127.0.0.1:57725/devtools/browser/97d0ba8b-e6ae-41b8-9186-f5f52bec75e8
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] got: {"sessionId":"23e78fc621d96429288fc15a65d545df","status":33,"value":{"message":"session not created: Chro
me version must be between 71 and 75\n  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)"}}
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] POST /session/23e78fc621d96429288fc15a65d545df/url {"url":"http://127.0.0.1:57721"}
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] got: {"sessionId":"23e78fc621d96429288fc15a65d545df","status":6,"value":{"message":"invalid session id\n  (Dri
ver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)"}}
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] POST /session/23e78fc621d96429288fc15a65d545df/element {"using":"css selector","value":"#output"}
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] got: {"sessionId":"23e78fc621d96429288fc15a65d545df","status":6,"value":{"message":"invalid session id\n  (Dri
ver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)"}}
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] DELETE /session/23e78fc621d96429288fc15a65d545df/window
[2019-08-13T14:39:21Z DEBUG wasm_bindgen_test_runner::headless] got: {"sessionId":"23e78fc621d96429288fc15a65d545df","status":6,"value":{"message":"invalid session id\n  (Dri
ver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18362 x86_64)"}}
driver status: exit code: 1
driver stdout:
    Starting ChromeDriver 2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1) on port 57722
    Only local connections are allowed.
    Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

error: failed to find element reference in response
error: test failed, to rerun pass '--test web'
Error: Running Wasm tests with wasm-bindgen-test failed
Caused by: failed to execute `cargo test`: exited with exit code: 1
```

**Comment by enzoc4** [comment] 2019-08-13 15:05
Well, it seems Chrome could not be started... The error seems to be this one:
`Chrome version must be between 71 and 75`
What version of Chrome are you using?

**Comment by dorin100** [comment] 2019-08-13 15:07
```
Google Chrome is up to date
Version 76.0.3809.100 (Official Build) (64-bit)
```

**Comment by rinor** [comment] 2019-08-13 15:44
The ChromeDriver 2.46 installed by wasm-pack does not support Chrome 76.0.xx.
If you download the correct version of ChromeDriver, all tests pass.

I downloaded the correct version from https://chromedriver.storage.googleapis.com/index.html?path=76.0.3809.68/

**Comment by NicolasDP** [comment] 2019-08-16 10:13
thanks @rinor . We can close this issue now.

**Closed by NicolasDP** 2019-08-16 10:13 UTC
